name = "nagaspace.beta"
pages_build_output_dir = "." #"public"
compatibility_date = "2025-11-02"

# --- D1 Database Binding (for storing ads) ---
[[d1_databases]]
binding = "DB"
database_name = "iotbase"
database_id = "5f9fa179-fa36-4cb9-8f07-c5d3505dc800"

# --- KV Namespace Binding (for caching / metadata) ---
[[kv_namespaces]]
binding = "USERS_KV"
id = "5c22090b5e354b59a562299681150df0"
